spring.application.name=sample001

# DBæ¥ç¶æå ±
spring.datasource.url=jdbc:h2:mem:crewdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2コンソール有効化
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPAè¨­å®
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Thymeleafè¨­å®ï¼å¿è¦ãªãï¼
spring.thymeleaf.cache=false