spring.application.name=sample001

# DB接続情報
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JPA設定
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf設定（必要なら）
spring.thymeleaf.cache=false